import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";

const geistSans = localFont({
  src: "./fonts/SkyText-Regular.ttf",
  variable: "--font-geist-sans-regular",
  weight: "400",
});

const geistSansItalic = localFont({
  src: "./fonts/SkyText-Italic.ttf",
  variable: "--font-geist-sans-light",
  weight: "300",
});
const geistMono = localFont({
  src: "./fonts/SkyText-Bold.ttf",
  variable: "--font-geist-mono",
  weight: "700 900",
});

const geistSansMedium = localFont({
  variable: "--font-geist-sans-mdeium",
  src: "./fonts/SkyText-Medium.ttf",
  weight: "600",
});

export const metadata: Metadata = {
  title: "Sky Sports",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSansItalic.variable} ${geistSans.variable} ${geistMono.variable} ${geistSansMedium.variable} w-[100vw] antialiased`}
      >
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
